### ISSUE TITLE
Request: Option to include file extension in displayed text

### ISSUE THREAD

**Issue by Sebert81** [alberti42/obsidian-import-attachments-plus#10]
Hi, 

it's me again :-)

Could you include an option to include the file extension when the filename is used for the displayed text?
Sometimes it is important to me to see if the file is a pdf or a docx ...

Regards & Thanks

**Comment by alberti42** [comment]
Yes, I will add the option.

**Comment by alberti42** [comment]
Please have a look at the new release: https://github.com/alberti42/obsidian-import-attachments-plus/releases/tag/1.5.11

**Comment by alberti42** [comment]
I close this issue because the feature has been implemented. I did not hear back from you. Please feel free to reopen the issue if you think something is missing.

**Comment by Sebert81** [comment]
Thank you.
