### ISSUE TITLE
Deleting the attachment folder automatically

### ISSUE THREAD

**Issue by Prynka1995** [alberti42/obsidian-import-attachments-plus#4]
Hi,
plugin don't delete the attachment folder automatically when the note is deleted.
![image](https://github.com/user-attachments/assets/c598a18b-05e8-4052-a140-a3991a80fd85)

What should I do?

**Comment by alberti42** [comment]
Thank you for pointing this out. It was a small typo (i.e. bug), which I corrected. You can update to the new version.

**Comment by Prynka1995** [comment]
Thanks a lot!
