### ISSUE TITLE
Issue: Drag & Drop does not work in canvas

### ISSUE THREAD

**Issue by Sebert81** [alberti42/obsidian-import-attachments-plus#8]
Hi,

I really like your plugin. It adds a lot of functionality that I've been missing. Thank you for that!

But: I use a lot of canvasses, and when your plugin is enabled i can't paste images from the clipboard
or drag & drop files (tried pdf, png & txt) onto the canvas.
Same goes for textboxes on the canvas: When I drag a file into it, nothing happens.

Regards 

Sebert

**Comment by alberti42** [comment]
Hi Sebert, I think the same issue was raised just a couple of days ago, https://github.com/alberti42/obsidian-import-attachments-plus/issues/6. I can say, it will for sure be fixed, possibly by the weekend. This week I am busy and have little time to look into it. I expect it to be a simple fix.

**Comment by Sebert81** [comment]
Sorry, did not see that / did not look properly.

**Comment by alberti42** [comment]
Here are the change logs: https://github.com/alberti42/obsidian-import-attachments-plus/releases

**Comment by alberti42** [comment]
> Delete Link and File only deletes the file, not the link. Happens when you directly drop a file unto the canvas and when you
add it to a card on the canvas.

I have now hidden the delete button to avoid confusion. The feature will be implemented in some feature release. For the moment, you have to delete the attachment manually.

Tip: You can use configure a short cut to directly open the attachment folder. Have a look at the bottom of the preference panes, it will bring you to the page where you can customize the hotkeys and assign a simple shortcut to open the attachment folder:

![Bildschirmfoto 2024-10-20 um 17 03 57](https://github.com/user-attachments/assets/1eb669ad-fc6c-4fad-af5a-dfd7c6a343fd)

![Bildschirmfoto 2024-10-20 um 17 04 43](https://github.com/user-attachments/assets/33ff07c1-045e-4623-8a55-a1052a0b2d3d)
