### ISSUE TITLE
The rename ${notename} variable for attachments name doesn't work

### ISSUE THREAD

**Issue by long369486562** [alberti42/obsidian-import-attachments-plus#9]
![image](https://github.com/user-attachments/assets/152c8ef7-2bf3-4b8c-a8c4-a2ac2f8b210f)

**Comment by alberti42** [comment]
Yes, ${notename} does not exist among the options below. Check your screenshot. You can only choose ${original} which stands for the original name of the attachment. I realize that the explanation was not very clear. I will change the info description in the next version of the plugin (though the functionality won't change).

```
${original} for the original name of the imported attachment
```

${notename} is used to specify the name of the attachment folder. I will change the description there to:

```
${notename} for the name of the MarkDown note to which the attachment files are imported
```

**Comment by alberti42** [comment]
This is how the description will appear in the next release:

![Bildschirmfoto 2024-10-09 um 07 47 07](https://github.com/user-attachments/assets/3d5a419f-8502-466e-822b-dd85ee1948a5)

![Bildschirmfoto 2024-10-09 um 07 47 16](https://github.com/user-attachments/assets/2c2cfd3d-3202-489a-aa91-1b0651bca4a1)

**Comment by long369486562** [comment]
I mean I wish I had this variable，I apologize for not being more explicit.

**Comment by alberti42** [comment]
Ah I see. Ok. Can you be patient until the weekend? I will add it and release the new version.

**Comment by long369486562** [comment]
That's certainly not a problem. Thank you.

**Comment by long369486562** [comment]
It is recommended to rename other imported attachments as well, and to support the use of this variable, which will enable easy identification of the attachment directory and all attached files by  notename，
I say this because I found that after dragging in other file attachments, the attachments are saved with their original names，

**Comment by alberti42** [comment]
I am not sure I understand your last comment. Possibly what you have in mind is using a single folder for importing attachments.

What I instead prefer is to use a subfolder carrying the same name of the note + (attachments):

![Bildschirmfoto 2024-10-09 um 10 29 38](https://github.com/user-attachments/assets/d68f243b-04a1-4004-a5d9-377230676dda)

and then I opt to hide those subfolders from the file navigator to keep a clean look:

![Bildschirmfoto 2024-10-09 um 10 29 08](https://github.com/user-attachments/assets/308e2aaa-bfbf-4f88-b6ec-0285787dbfd3)

**Comment by long369486562** [comment]
I apologize for the confusion, as importing other attachments when there was only ${original} resulted in the original name, and I mistakenly thought that there was no rename step when importing other attachments, only to find out that there already was!

**Comment by long369486562** [comment]
You can close this feedback now after you receive my apology

**Comment by long369486562** [comment]
> Ah I see. Ok. Can you be patient until the weekend? I will add it and release the new version.

this variable  ${notename}   .... gaga

**Comment by alberti42** [comment]
What do you mean?

**Comment by alberti42** [comment]
I added the requested feature. Please have a look at the new release: https://github.com/alberti42/obsidian-import-attachments-plus/releases/tag/1.5.11

**Comment by alberti42** [comment]
I did not receive a feedback. Because the feature is implemented, I will close the issue. Feel free to reopen it if I missed something.
